# Generated by Django 4.1.3 on 2022-12-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='stype',
            new_name='style',
        ),
    ]
